# example netlify.toml
[build]
  command = "yarn build"
  functions = "functions/dist/functions"
  publish = "dist"

  # shorthand api path redirect
  [[redirects]]
   from = "/api/*"
   to = "/.netlify/functions/studio-api/:splat"
   status = 200

  # redirect for Single Page Applications
  [[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200

  # (optional) Settings for Netlify Dev
  # https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  [dev]
   command = "yarn devrun" # Command to start your dev server
   port = 7447 # Port that the dev server will be listening on
   targetPort = 3000
   publish = "dist" # Folder with the static content for _redirect file
   functionsPort = 8888

  # more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
